%  Union Feature Matrix and Property Vector to Structure-Property-Data
%  Johns Hopkins University
%  Shengzhi Luan
%  02.08.2023
% =========================================================================
Feature_Matrix_Modulus = [];
Property_Vector_Modulus = [];
%  ------------------------------------------------------------------------
cd('Feature_Property_Output');
for i = 1:1:17
    Feature_String = strcat('Feature_Matrix_',num2str(i),'.txt');
    Property_String = strcat('Property_Vector_',num2str(i),'.txt');
    Feature_Matrix = load(Feature_String);
    Property_Vector = load(Property_String);
    Feature_Matrix_Modulus = [Feature_Matrix_Modulus;Feature_Matrix];
    Property_Vector_Modulus = [Property_Vector_Modulus;Property_Vector];
end
%  ------------------------------------------------------------------------
Nan_Flag = isnan(Feature_Matrix_Modulus);
for i = 1:1:size(Feature_Matrix_Modulus,1)
    for j = 1:1:size(Feature_Matrix_Modulus,2)
        if Nan_Flag(i,j) == 1
            if ismember(j,[5:4:41]) == 1
                Feature_Matrix_Modulus(i,j) = 0;
            end
        end
    end
end
Nan_Flag = isnan(Feature_Matrix_Modulus);
Feature_Matrix_Modulus_Correction = zeros(size(Feature_Matrix_Modulus));
for i = 1:1:size(Feature_Matrix_Modulus,1)
    for j = 1:1:size(Feature_Matrix_Modulus,2)
        if Nan_Flag(i,j) == 1
            Pause_Coe = i;
            while Nan_Flag(Pause_Coe,j) == 1
                Pause_Coe = Pause_Coe + 1;
                if Nan_Flag(Pause_Coe,j) == 0
                    Feature_Matrix_Modulus_Correction(i,j) = ...
                                  Feature_Matrix_Modulus(Pause_Coe,j)*1.25;
                end
            end
        end
    end
end
%  ------------------------------------------------------------------------
for i = 1:1:size(Feature_Matrix_Modulus,1)
    for j = 1:1:size(Feature_Matrix_Modulus,2)
        if Nan_Flag(i,j) == 1
            Feature_Matrix_Modulus(i,j) = ...
                    Feature_Matrix_Modulus_Correction(i,j);
        end
    end
end
%  ------------------------------------------------------------------------
Structure_Property_Data = [Feature_Matrix_Modulus,Property_Vector_Modulus];
Table = array2table(Structure_Property_Data);
Table.Properties.VariableNames = {'Relative density', ...
                                  'Number of polygonal cells', ...
                                  'Mean of cell edge number', ...
                                  'Variance of cell edge number', ...
                                  'Skewness of cell edge number', ...
                                  'Kurtosis of cell edge number', ...
                                  'Mean of cell area', ...
                                  'Variance of cell area', ...
                                  'Skewness of cell area', ...
                                  'Kurtosis of cell area', ...
                                  'Mean of cell compactness', ...
                                  'Variance of cell compactness', ...
                                  'Skewness of cell compactness', ...
                                  'Kurtosis of cell compactness', ...
                                  'Mean of cell eccentricity', ...
                                  'Variance of cell eccentricity', ...
                                  'Skewness of cell eccentricity', ...
                                  'Kurtosis of cell eccentricity', ...
                                  'Mean of strut length', ...
                                  'Variance of strut length', ...
                                  'Skewness of strut length', ...
                                  'Kurtosis of strut length', ...
                                  'Mean of strut orientation', ...
                                  'Variance of strut orientation', ...
                                  'Skewness of strut orientation', ...
                                  'Kurtosis of strut orientation', ...
                                  'Mean of nodal connectivity', ...
                                  'Variance of nodal connectivity', ...
                                  'Skewness of nodal connectivity', ...
                                  'Kurtosis of nodal connectivity', ...
                          'Mean of neighboring seed distance', ...
                          'Variance of neighboring seed distance', ...
                          'Skewness of neighboring seed distance', ...
                          'Kurtosis of neighboring seed distance', ...
                          'Mean of neighboring seed angle sine', ...
                          'Variance of neighboring seed angle sine', ...
                          'Skewness of neighboring seed angle sine', ...
                          'Kurtosis of neighboring seed angle sine', ...
                          'Mean of neighboring seed angle cosine', ...
                          'Variance of neighboring seed angle cosine', ...
                          'Skewness of neighboring seed angle cosine', ...
                          'Kurtosis of neighboring seed angle cosine', ...
                          'Relative stiffness'};
writetable(Table,'Structure-Property-Data.csv');
cd ..
% =========================================================================